# Site settings
baseurl = "/"
languageCode = "cz-CZ"
title = "Právní překlady"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Kateřina Kutnerová - právní překlady"
  description = "Právní překlady a tlumočení z a do němčiny."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Právní překlady"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Služby"
    portfolio = "Portfolio"
    about = "O nás"
    team = "Tým"
    contact = "Kontakt"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://www.activlingua.cz"
      name = "ActivLingua"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Soudně ověřené překlady a tlumočení"
    subtitle = "německého jazyka"
    buttonText = "Řekni mi víc"


  # Services section
  [params.services]
    enable = true
    title = "Služby"
    subtitle = "Vždy profesionální, spolehlivé a diskrétní."

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-globe"
      title = "Překlady"
      description = """Nabízím běžné, ale i soudně ověřené překlady z/do němčiny. Provádím především překlady právních textů jako jsou například překlady smluv, obchodních podmínek, úředních listin (rodné listy, oddací listy, výpisy z obchodního rejstříku, výpisy z rejstříku trestů, diplomy apod.) a soudních dokumentů. <br><br>
      Mými klienti jsou často české i zahraniční firmy, takže se velmi často setkávám s překlady obchodní dokumentace, s překlady návodů, cenových nabídek, protokolů, účetních uzávěrek, zadávací dokumentace, s překlady technické dokumentace apod. <br><br> 
      Pro vytvoření přesné cenové nabídky a stanovaní termínu dodání potřebuji znát konkrétní překládaný text. Zašlete mi ho a v co nejkratší možné době obdržíte konkrétní cenu i reálný termín dodání. V ceně překladu je již zahrnuta cena základní jazykové korektury. <br><br> Při kontaktu s klientem se vždy snažím o individuální přístup tak, abych klientovi maximálně vyhověla. Platební i časové podmínky vždy domluvíme předem, aby byla zajištěna maximální kvalita a spokojenost zákazníka."""
      url = "#"

	[[params.services.row.list]]
      icon = "fa-gavel"
      title = "Soudní překlady"
      description = """Ověřený (neboli soudní) překlad je překlad opatřený kulatým razítkem a podpisem soudního překladatele a je svázaný většinou s originální listinou (případně její ověřenou kopií). Ověřené překlady většinou potřebujete při komunikaci s úřady, při žádostech o práci v zahraničí, při sňatku s osobou jiné státní příslušnosti, při uzavírání mezinárodních smluv apod. <br><br> 
      Po absolvování germanistiky a bohemistiky na Filozovické fakultě Masarykovy Univerzity a Doplňkového studia pro soudní tlumočníky a překladatele na Právnické fakultě Univerzity Karlovy jsem byla v roce 2009 jmenována soudním tlumočníkem a překladatelem. <br><br>
      Pokud tedy potřebujete ověřené překlady z/do němčiny, jsem tu, abych Vám pomohla. <br><br>
      Nejčastější překlady listin:

- překlad rodného listu
- překlad oddacího listu
- překlad diplomů a vysvědčení
- překlad smluv, plných mocí
- překlad výpisů z rejstříku trestů
- překlad výpisů z obchodního rejstříku
- atd.
      """
      url = "#"
	  
    [[params.services.row.list]]
      icon = "fa-comments"
      title = "Tlumočení"
      description = """Pokud potřebujete vést např. obchodní jednání nebo prezentaci v jiném jazyce, nabízím Vám konsekutivní tlumočení. Při mé práci tlumočníka často doprovázím zástupce firem např. na různá školení, prohlídky provozoven a podniků, na výstavy a veletrhy, obchodní prezentace a jednání. Při tlumočení se vždy snažím o to, aby si obě strany maximálné porozumněly a uměly vyřešit všechny problémy a úskalí. <br><br> 
      Tlumočníka budete také potřebovat např. při svatebím obřadu s osobou jiné státní příslušnosti. I pro tyto příležitosti jsem Vám k dispozici."""
      url = "#"

  # Portfolio section
  [params.portfolio]
    enable = false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    subtitle = "Lorem ipsum dolor sit amet consectetur."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = true
    title = "O mně"
    subtitle = "Mgr. Kateřina Kutnerová"
    endpoint = "Překládejte<br>s<br>námi!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "1999-2005"
      title = "Filozofická fakulta MU"
      description = "Magisterské studium germanistiky a bohemistiky"
	  
    [[params.about.events]]
      img = "2.jpg"
      date = "2001"
      title = "Zahájení živnosti"
      description = "Překlady, tlumočení, lektorská činnost"
	
	[[params.about.events]]
      img = "2.jpg"
      date = "2001 - 2009"
      title = "Studijní jazykové pobyty"
      description = "Německo, Rakousko, Rusko, Ukrajina"  
	  
    [[params.about.events]]
      img = "3.jpg"
      date = "2009"
      title = "Univerzita Karlova - Juridikum"
      description = "Doplňkové studium pro soudní překladatele a tlumočníky"
	  
	[[params.about.events]]
      img = "4.jpg"
      date = "2009"
      title = "Jmenováním soudním překladatelem a tlumočníkem"
      description = ""  

	[[params.about.events]]
      img = "4.jpg"
      date = "2009"
      title = "ActivLingua"
      description = "Založení jazykové agentury se specializací němčina, ruština, angličtina"  	  

  # Team section
  [params.team]
    enable = false
    # Possibility to center items
    #center = true
    title = "Náš skvělý tým"
    subtitle = "Tohle jsme my. Těšíme se na Vás."
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "1.jpg"
      name = "Kateřina Kutnerová"
      position = "Ředitelka"
      reportsTo = "CTO"
      livesIn = "[Kanice, Česká republika](#some-maps-url)"
      scope = [
        "UX for [member dashboard](#)",
        "Maintainer for [awesome-project](#)",
        "Open Source [community management](#)"
      ]
      # For bio markdown and even multiline strings are available.
      bio = """Kačenka je úplně nejvíc nejlepší."""
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Larry Parker"
      position = "Lead Marketer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "3.jpg"
      name = "Diana Pertersen"
      position = "Lead Developer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Kontaktujte nás"
    subtitle  = '''Pošlete svou zprávu nebo svůj dotaz, ozveme se vám.<br>
	Mgr. Kateřina Kutnerová<br>
	Kanice 316<br>
	664 01<br>
	tel: +420 724 026 913<br>
	mail: <a href=mailto:katerina@pravnipreklady.eu>katerina@pravnipreklady.eu</a>'''
    buttonText = "Poslat zprávu"
	  netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "lukas@kutner.cz"

    # Success and error message overwrite for async contact form
    thanks = "Děkujeme za zprávu, co nejdřive se Vám ozveme."
    error = "Zpráva nemohla být odeslána, kontaktujte nás prosím na emailu <a href=mailto:katerina@pravnipreklady.eu>katerina@pravnipreklady.eu</a> nebo telefonicky."

    #[params.contact.captcha]
		#sitekey = "6Lc5LFwUAAAAAHl9LbpCvwwICkKh4TdEe8Q0lveH"

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Vaše jméno *"
      warning = "Prosím zadejte Vaše jméno."

    [params.contact.form.email]
      text = "Vaše emailová adresa *"
      warning = "Prosím zadejte Vaší emailovou adresu."

    [params.contact.form.phone]
      text = "Vaše telefonní číslo *"
      warning = "Prosím zadejte Vaše telefonní číslo."

    [params.contact.form.message]
      text = "Vaše zpráva *"
      warning = "Prosím napište zprávu."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "https://cz.linkedin.com/in/kutnerova"
      title = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
